baseURL = "https://deploycraft.io/"
languageCode = "en-us"
title = "DeployCraft.io"
enableRobotsTXT = true
canonifyURLs = true

[params]
  description = "In-depth DevSecOps and CI/CD coverage for Kubernetes practitioners"
  author = "DeployCraft.io"
  email = "hello@deploycraft.io"
  github = "https://github.com/victord-ef"
  linkedin = "https://linkedin.com/company/deploycraft"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style       = "dracula"
    lineNos     = false
    codeFences  = true
    guessSyntax = true

[minify]
  disableXML   = false
  minifyOutput = true
