feeds:
  - name: OpenAI
    url: https://openai.com/news/rss.xml

  - name: Kubernetes
    url: https://kubernetes.io/feed.xml

  - name: CNCF Announcements
    url: https://www.cncf.io/category/announcements/feed/

  - name: AWS What's New
    url: https://aws.amazon.com/about-aws/whats-new/recent/feed/
